// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Musala.Tests.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Musala Tests")]
    public partial class MusalaTestsFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Tests/Features", "Musala Tests", null, ProgrammingLanguage.CSharp, featureTags);
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Verify invalid email address validation on Contact Us page")]
        [NUnit.Framework.TestCaseAttribute("Email:The e-mail address entered is invalid.", "Name,invalid@email,02,Subject,Message", null)]
        public void VerifyInvalidEmailAddressValidationOnContactUsPage(string errorMessage, string data, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("Error Message", errorMessage);
            argumentsOfScenario.Add("Data", data);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Verify invalid email address validation on Contact Us page", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                testRunner.Given("the user is on the landing page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
                testRunner.When("the user goes to Contact Us from the landing page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
                testRunner.When(string.Format("the user populates Apply For form with \'{0}\'", data), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
                testRunner.And("the user clicks the Send button in the Contact Us dialog", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
                testRunner.Then(string.Format("an error messages for \'{0}\' appear in the dialog", errorMessage), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Verify Leadership section and company Facebook page link")]
        public void VerifyLeadershipSectionAndCompanyFacebookPageLink()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Verify Leadership section and company Facebook page link", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                testRunner.Given("the user is on the landing page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
                testRunner.When("the user selects \'Company\' section in the top navigation", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
                testRunner.Then("the user verifies \'https://www.musala.com/company/\' is the expected URL", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
                testRunner.Then("the user verifies there is a Leadership section", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
                testRunner.When("the user clicks Facebook link from the footer", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
                testRunner.Then("the user verifies \'https://www.facebook.com/MusalaSoft?fref=ts\' is the expected U" +
                        "RL", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
                testRunner.Then("the Musala Soft profile picture appears on the Facebook page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Verify validation error messages on Join Us dialog")]
        [NUnit.Framework.TestCaseAttribute("asd,asd@asd,123123,..\\..\\..\\CV.doc,asd", "Email:The e-mail address entered is invalid.", "One or more fields have an error. Please check and try again.", null)]
        [NUnit.Framework.TestCaseAttribute("Name,Email,Mobile,,", "Email:The e-mail address entered is invalid.,Phone:The telephone number is invali" +
            "d.", "One or more fields have an error. Please check and try again.", null)]
        [NUnit.Framework.TestCaseAttribute(",Email@abv.bg,,,Hello", "Name:The field is required.,Phone:The field is required.", "One or more fields have an error. Please check and try again.", null)]
        public void VerifyValidationErrorMessagesOnJoinUsDialog(string data, string message, string generalMessage, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("Data", data);
            argumentsOfScenario.Add("Message", message);
            argumentsOfScenario.Add("GeneralMessage", generalMessage);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Verify validation error messages on Join Us dialog", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                testRunner.Given("the user is on the landing page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
                testRunner.When("the user selects \'Careers\' section in the top navigation", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
                testRunner.When("the user clicks ‘Check our open positions’ button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
                testRunner.Then("the user verifies \'https://www.musala.com/careers/join-us/\' is the expected URL", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
                testRunner.When("the user selects \'Anywhere\' in the Location Filter on Join Us page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
                testRunner.When("the user selects \'Automation QA Engineer\' position from the list on Join Us page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
                testRunner.Then("the user verifies there is a \'General description,Requirements,Responsibilities,W" +
                        "hat we offer\' section shown in the Job page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
                testRunner.Then("Apply CTA is present on the Job page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
                testRunner.When("the user clicks Apply CTA on the Job page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
                testRunner.When(string.Format("the user populates Apply For form with \'{0}\'", data), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
                testRunner.Then(string.Format("an error messages for \'{0}\' appear in the dialog", message), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
                testRunner.When("the user clicks Send CTA in the Apply Form", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
                testRunner.Then(string.Format("an error messages for \'{0}\' appear in the dialog", generalMessage), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Return list of available positions by city")]
        [NUnit.Framework.CategoryAttribute("parallel")]
        public void ReturnListOfAvailablePositionsByCity()
        {
            string[] tagsOfScenario = new string[] {
                    "parallel"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Return list of available positions by city", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                testRunner.Given("the user is on the landing page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
                testRunner.When("the user selects \'Careers\' section in the top navigation", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
                testRunner.When("the user clicks ‘Check our open positions’ button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
                testRunner.Then("Print all available positions for \'Bulgaria\' location", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
                testRunner.Then("Print all available positions for \'Egypt\' location", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
            }
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
